name: relyance-sci

on:
  schedule:
    - cron: "0 20 * * *"
  workflow_dispatch:

jobs:
  execute-relyance-sci:
    name: Relyance SCI Job
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull and run SCI binary
        run: |-app_0534e0cad1d771cf670b8dd93815e28d
          docker pull gcr.io/relyance-ext/compliance_inspector:release && \
          docker run --rm -v `pwd`:/repo --env API_KEY='matthew-rodriguez' gcr.io/relyance-ext/compliance_inspector:release
